env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[57dc7c3a2a22c6793e5e764134b9378ff9b89b66f381ba5748a4bc69b24af8c36032953582ee16db3d988cc925cdb860]"
  TG_TOKEN: "ENCRYPTED[0fbc88cdc364e3041bf22841dfd3c053e3a51e97081fa932aeb35040eb2b8fce87e15b4ce35ff811948d16aa73fb8c0a]"
  TG_CHAT_ID: "ENCRYPTED[6891a0c3b33d8c74cedbf2c7b6682e58b783d392f781ecbfe08d924dcf89b86f7a3c1b276e11878e9c292fb011a9126d]"
  WORKDIR: "/tmp"
  EMAIL: "ENCRYPTED[869864d36bb6859156d490d08cc3b197b6a49afc0caf3da9c9f9bef456fe86be333a45d81263767c4388d430d0d1a9cd]"
  CIRRUS_CLONE_DEPTH: "1"
  credentials: "ENCRYPTED[b5cc9cfc03ba04507e78432058852817b69754101c47ae5c3ac63e0c89dd889595013f997d49ac4081623952ac47fdff]"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'zacky46'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "zacky46"
     - git config --global user.email "zacky46@gmail.com"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
